export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const SET_USER_DATA = 'SET_USER_DATA';

export const LOGOUT = 'LOGOUT';

export const LOADER_START = 'LOADER_START';
export const LOADER_STOP = 'LOADER_STOP';

export const CHANGE_BIRTHDAY_PERSON_NAME = 'CHANGE_BIRTHDAY_PERSON_NAME';
export const CHANGE_BIRTHDAY_DATE = 'CHANGE_BIRTHDAY_DATE';

export const ADD_BIRTHDAY_ITEM_START = 'ADD_BIRTHDAY_ITEM_START';
export const ADD_BIRTHDAY_ITEM_SUCCESS = 'ADD_BIRTHDAY_ITEM_SUCCESS';
export const ADD_BIRTHDAY_ITEM_FAIL = 'ADD_BIRTHDAY_ITEM_FAIL';

export const DELETE_BIRTHDAY_ITEM_START = 'DELETE_BIRTHDAY_ITEM_START';
export const DELETE_BIRTHDAY_ITEM_SUCCESS = 'DELETE_BIRTHDAY_ITEM_SUCCESS';
export const DELETE_BIRTHDAY_ITEM_FAIL = 'DELETE_BIRTHDAY_ITEM_FAIL';

export const SAVE_BIRTHDAY_DATA = 'SAVE_BIRTHDAY_DATA';
export const DELETE_BIRTHDAY_DATA = 'DELETE_BIRTHDAY_DATA';
export const SET_BIRTHDAY_DATA = 'SET_BIRTHDAY_DATA';
